""""""""""""""""""""""""""""""""""""""""""
" Archivo de configuracion neovim windows 
""""""""""""""""""""""""""""""""""""""""""

" Change leader to a comma because the backslash is too far away
" That means all \x commands turn into ,x
" The mapleader has to be set before vundle starts loading all 
" the plugins.
let mapleader=","


" Archivo de configuracion del usuario
if filereadable(expand("~/.vimrc.before"))
  source ~/.vimrc.before
endif


set nocompatible
filetype off

set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

Plugin 'bundle/VundleVim/Vundle.vim'

source vundles.vim

call vundle#end()
filetype plugin indent on


" Añadimos settings de los plugins
let vimplugsettings="~/.vim/plugsettings"
for fpath in split(globpath(vimplugsettings, '*.vim'), '\n')
  exe 'source' fpath
endfor


" Añadimos settings
let vimsettings="~/.vim/settings"
for fpath in split(globpath(vimsettings, '*.vim'), '\n')
  exe 'source' fpath
endfor

colorscheme railscasts


" Archivo de configuracion del usuario
if filereadable(expand("~/.vimrc.after"))
  source ~/.vimrc.after
endif
